
package com.springboot.study.service.springairline;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2017-11-23T10:01:49.227+08:00
 * Generated source version: 3.2.1
 * 
 */
public final class SpringServiceSearchBookInterface_SpringServiceSearchBookInterfacePort_Client {

    private static final QName SERVICE_NAME = new QName("http://wsinterface.remoteservice.booking.springairlines.com/", "SpringServiceSearchBookInterfaceService");

    private SpringServiceSearchBookInterface_SpringServiceSearchBookInterfacePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SpringServiceSearchBookInterfaceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SpringServiceSearchBookInterfaceService ss = new SpringServiceSearchBookInterfaceService(wsdlURL, SERVICE_NAME);
        SpringServiceSearchBookInterface port = ss.getSpringServiceSearchBookInterfacePort();  
        
        {
        System.out.println("Invoking getInvoice...");
        com.springboot.study.service.springairline.ReqBeanOfGetInvoice _getInvoice_reqBean = null;
        com.springboot.study.service.springairline.RetBeanofGetInvoice _getInvoice__return = port.getInvoice(_getInvoice_reqBean);
        System.out.println("getInvoice.result=" + _getInvoice__return);


        }
        {
        System.out.println("Invoking getSubProdBySeg...");
        com.springboot.study.service.springairline.GetSubProdBySegInputBean _getSubProdBySeg_searchInfo = null;
        com.springboot.study.service.springairline.GetSubProdBySegResultBean _getSubProdBySeg__return = port.getSubProdBySeg(_getSubProdBySeg_searchInfo);
        System.out.println("getSubProdBySeg.result=" + _getSubProdBySeg__return);


        }
        {
        System.out.println("Invoking searchFlightsBatch...");
        com.springboot.study.service.springairline.SearchFlightsBatchSearchBean _searchFlightsBatch_searchInfo = null;
        com.springboot.study.service.springairline.SearchFlightsBatchResultBean _searchFlightsBatch__return = port.searchFlightsBatch(_searchFlightsBatch_searchInfo);
        System.out.println("searchFlightsBatch.result=" + _searchFlightsBatch__return);


        }
        {
        System.out.println("Invoking bookOrder...");
        com.springboot.study.service.springairline.BookOrderBookBean _bookOrder_bookInfo = null;
        com.springboot.study.service.springairline.BookOrderResultBean _bookOrder__return = port.bookOrder(_bookOrder_bookInfo);
        System.out.println("bookOrder.result=" + _bookOrder__return);


        }
        {
        System.out.println("Invoking getMoneyClass...");
        com.springboot.study.service.springairline.GetMoneyClassSearchBean _getMoneyClass_searchInfo = null;
        com.springboot.study.service.springairline.GetMoneyClassResultBean _getMoneyClass__return = port.getMoneyClass(_getMoneyClass_searchInfo);
        System.out.println("getMoneyClass.result=" + _getMoneyClass__return);


        }
        {
        System.out.println("Invoking getKeguiTotalDescription...");
        com.springboot.study.service.springairline.GetKeguiTotalDescriptionInputBean _getKeguiTotalDescription_searchInfo = null;
        com.springboot.study.service.springairline.GetKeguiTotalDescriptionResultBean _getKeguiTotalDescription__return = port.getKeguiTotalDescription(_getKeguiTotalDescription_searchInfo);
        System.out.println("getKeguiTotalDescription.result=" + _getKeguiTotalDescription__return);


        }
        {
        System.out.println("Invoking submitFlightBgApp2...");
        com.springboot.study.service.springairline.SubmitFlightBgAppInputBean _submitFlightBgApp2_searchInfo = null;
        com.springboot.study.service.springairline.SubmitFlightBgAppResultBean _submitFlightBgApp2__return = port.submitFlightBgApp2(_submitFlightBgApp2_searchInfo);
        System.out.println("submitFlightBgApp2.result=" + _submitFlightBgApp2__return);


        }
        {
        System.out.println("Invoking createInvoice...");
        com.springboot.study.service.springairline.ReqBeanOfCreateInvoice _createInvoice_reqBean = null;
        com.springboot.study.service.springairline.RetBeanofCreateInvoice _createInvoice__return = port.createInvoice(_createInvoice_reqBean);
        System.out.println("createInvoice.result=" + _createInvoice__return);


        }
        {
        System.out.println("Invoking getFlightsCanBg...");
        com.springboot.study.service.springairline.GetFlightsCanBgInputBean _getFlightsCanBg_searchInfo = null;
        com.springboot.study.service.springairline.GetFlightsCanBgResultBean _getFlightsCanBg__return = port.getFlightsCanBg(_getFlightsCanBg_searchInfo);
        System.out.println("getFlightsCanBg.result=" + _getFlightsCanBg__return);


        }
        {
        System.out.println("Invoking applyReturnTicket2...");
        com.springboot.study.service.springairline.ApplyReturnTicketInputBean _applyReturnTicket2_appInfo = null;
        com.springboot.study.service.springairline.ApplyReturnTicketResultBean2 _applyReturnTicket2__return = port.applyReturnTicket2(_applyReturnTicket2_appInfo);
        System.out.println("applyReturnTicket2.result=" + _applyReturnTicket2__return);


        }
        {
        System.out.println("Invoking getFlightBgApp...");
        com.springboot.study.service.springairline.GetFlightBgAppInputBean _getFlightBgApp_searchInfo = null;
        com.springboot.study.service.springairline.GetFlightBgAppResultBean _getFlightBgApp__return = port.getFlightBgApp(_getFlightBgApp_searchInfo);
        System.out.println("getFlightBgApp.result=" + _getFlightBgApp__return);


        }
        {
        System.out.println("Invoking getKeguiTotalDescription2...");
        com.springboot.study.service.springairline.GetKeguiTotalDescriptionInputBean _getKeguiTotalDescription2_searchInfo = null;
        com.springboot.study.service.springairline.GetKeguiTotalDescriptionResultBean _getKeguiTotalDescription2__return = port.getKeguiTotalDescription2(_getKeguiTotalDescription2_searchInfo);
        System.out.println("getKeguiTotalDescription2.result=" + _getKeguiTotalDescription2__return);


        }
        {
        System.out.println("Invoking queryOrderInfoForSlt...");
        com.springboot.study.service.springairline.QueryOrderInfoForSltQueryBean _queryOrderInfoForSlt_queryInfo = null;
        com.springboot.study.service.springairline.QueryOrderInfoForSltResultBean _queryOrderInfoForSlt__return = port.queryOrderInfoForSlt(_queryOrderInfoForSlt_queryInfo);
        System.out.println("queryOrderInfoForSlt.result=" + _queryOrderInfoForSlt__return);


        }
        {
        System.out.println("Invoking applyReturnTicket...");
        com.springboot.study.service.springairline.ApplyReturnTicketInputBean _applyReturnTicket_appInfo = null;
        com.springboot.study.service.springairline.ApplyReturnTicketResultBean _applyReturnTicket__return = port.applyReturnTicket(_applyReturnTicket_appInfo);
        System.out.println("applyReturnTicket.result=" + _applyReturnTicket__return);


        }
        {
        System.out.println("Invoking calcRetTktFee...");
        com.springboot.study.service.springairline.CalcRetTktFeeInputBean _calcRetTktFee_calcInfo = null;
        com.springboot.study.service.springairline.CalcRetTktFeeResultBean _calcRetTktFee__return = port.calcRetTktFee(_calcRetTktFee_calcInfo);
        System.out.println("calcRetTktFee.result=" + _calcRetTktFee__return);


        }
        {
        System.out.println("Invoking searchFlightsBySegId...");
        com.springboot.study.service.springairline.SearchFlightsBySegIdBean _searchFlightsBySegId_searchInfo = null;
        com.springboot.study.service.springairline.SearchFlightsBatchResultBean _searchFlightsBySegId__return = port.searchFlightsBySegId(_searchFlightsBySegId_searchInfo);
        System.out.println("searchFlightsBySegId.result=" + _searchFlightsBySegId__return);


        }
        {
        System.out.println("Invoking getOrderDetailInfo...");
        com.springboot.study.service.springairline.GetOrderDetailInfoQueryBean _getOrderDetailInfo_queryInfo = null;
        com.springboot.study.service.springairline.GetOrderDetailInfoResultBean _getOrderDetailInfo__return = port.getOrderDetailInfo(_getOrderDetailInfo_queryInfo);
        System.out.println("getOrderDetailInfo.result=" + _getOrderDetailInfo__return);


        }
        {
        System.out.println("Invoking queryFlightBgAppInfo...");
        com.springboot.study.service.springairline.QueryFlightBgAppInfoInputBean _queryFlightBgAppInfo_searchInfo = null;
        com.springboot.study.service.springairline.QueryFlightBgAppInfoResultBean _queryFlightBgAppInfo__return = port.queryFlightBgAppInfo(_queryFlightBgAppInfo_searchInfo);
        System.out.println("queryFlightBgAppInfo.result=" + _queryFlightBgAppInfo__return);


        }
        {
        System.out.println("Invoking searchFlightsBatchSP...");
        com.springboot.study.service.springairline.SearchBeanOfSearchFlightsSP _searchFlightsBatchSP_searchInfo = null;
        com.springboot.study.service.springairline.SearchFlightsBatchResultBean _searchFlightsBatchSP__return = port.searchFlightsBatchSP(_searchFlightsBatchSP_searchInfo);
        System.out.println("searchFlightsBatchSP.result=" + _searchFlightsBatchSP__return);


        }
        {
        System.out.println("Invoking queryEInvoiceOrders...");
        com.springboot.study.service.springairline.ReqBeanOfTktDetail _queryEInvoiceOrders_reqBean = null;
        com.springboot.study.service.springairline.RetBeanOfTktDetail _queryEInvoiceOrders__return = port.queryEInvoiceOrders(_queryEInvoiceOrders_reqBean);
        System.out.println("queryEInvoiceOrders.result=" + _queryEInvoiceOrders__return);


        }
        {
        System.out.println("Invoking getTravelBaoJiDetailInfo...");
        com.springboot.study.service.springairline.GetTravelBaoJiDetailInfoQueryBean _getTravelBaoJiDetailInfo_queryInfo = null;
        com.springboot.study.service.springairline.GetTravelBaoJiDetailInfoResultBean _getTravelBaoJiDetailInfo__return = port.getTravelBaoJiDetailInfo(_getTravelBaoJiDetailInfo_queryInfo);
        System.out.println("getTravelBaoJiDetailInfo.result=" + _getTravelBaoJiDetailInfo__return);


        }
        {
        System.out.println("Invoking getOtherFyDetail...");
        com.springboot.study.service.springairline.GetOtherFyDetailInputBean _getOtherFyDetail_searchInfo = null;
        com.springboot.study.service.springairline.GetOtherFyDetailResultBean _getOtherFyDetail__return = port.getOtherFyDetail(_getOtherFyDetail_searchInfo);
        System.out.println("getOtherFyDetail.result=" + _getOtherFyDetail__return);


        }
        {
        System.out.println("Invoking cancelOrder...");
        com.springboot.study.service.springairline.CancelOrderInputBean _cancelOrder_cancelInfo = null;
        com.springboot.study.service.springairline.CancelOrderResultBean _cancelOrder__return = port.cancelOrder(_cancelOrder_cancelInfo);
        System.out.println("cancelOrder.result=" + _cancelOrder__return);


        }
        {
        System.out.println("Invoking searchFlightsBySegId2...");
        com.springboot.study.service.springairline.SearchFlightsBySegIdBean _searchFlightsBySegId2_searchInfo = null;
        com.springboot.study.service.springairline.SearchFlightsBatchResultBean2 _searchFlightsBySegId2__return = port.searchFlightsBySegId2(_searchFlightsBySegId2_searchInfo);
        System.out.println("searchFlightsBySegId2.result=" + _searchFlightsBySegId2__return);


        }
        {
        System.out.println("Invoking submitFlightBgApp...");
        com.springboot.study.service.springairline.SubmitFlightBgAppInputBean _submitFlightBgApp_searchInfo = null;
        com.springboot.study.service.springairline.SubmitFlightBgAppResultBean _submitFlightBgApp__return = port.submitFlightBgApp(_submitFlightBgApp_searchInfo);
        System.out.println("submitFlightBgApp.result=" + _submitFlightBgApp__return);


        }
        {
        System.out.println("Invoking getXprodCheckBind...");
        com.springboot.study.service.springairline.XprodBeanOfCheckBindInputBean _getXprodCheckBind_searchInfo = null;
        com.springboot.study.service.springairline.XprodBeanOfCheckBindResultBean _getXprodCheckBind__return = port.getXprodCheckBind(_getXprodCheckBind_searchInfo);
        System.out.println("getXprodCheckBind.result=" + _getXprodCheckBind__return);


        }
        {
        System.out.println("Invoking getSubProdBooked...");
        com.springboot.study.service.springairline.InfoBeanOfGetSubProdBooked _getSubProdBooked_searchInfo = null;
        com.springboot.study.service.springairline.GetSubProdBookedResultBean _getSubProdBooked__return = port.getSubProdBooked(_getSubProdBooked_searchInfo);
        System.out.println("getSubProdBooked.result=" + _getSubProdBooked__return);


        }
        {
        System.out.println("Invoking getTravelBaoJiDetailInfo1...");
        com.springboot.study.service.springairline.GetTravelBaoJiDetailInfoQueryBean _getTravelBaoJiDetailInfo1_queryInfo = null;
        com.springboot.study.service.springairline.GetTravelBaoJiDetailInfoResultBean1 _getTravelBaoJiDetailInfo1__return = port.getTravelBaoJiDetailInfo1(_getTravelBaoJiDetailInfo1_queryInfo);
        System.out.println("getTravelBaoJiDetailInfo1.result=" + _getTravelBaoJiDetailInfo1__return);


        }
        {
        System.out.println("Invoking cancelFlightBgApp...");
        com.springboot.study.service.springairline.CancelFlightBgAppInputBean _cancelFlightBgApp_cancelInfo = null;
        com.springboot.study.service.springairline.CancelFlightBgAppResultBean _cancelFlightBgApp__return = port.cancelFlightBgApp(_cancelFlightBgApp_cancelInfo);
        System.out.println("cancelFlightBgApp.result=" + _cancelFlightBgApp__return);


        }
        {
        System.out.println("Invoking bookOrderSubCabin...");
        com.springboot.study.service.springairline.BookOrderBookSubCabinBean _bookOrderSubCabin_bookOrderSubCabin = null;
        com.springboot.study.service.springairline.BookOrderResultBean _bookOrderSubCabin__return = port.bookOrderSubCabin(_bookOrderSubCabin_bookOrderSubCabin);
        System.out.println("bookOrderSubCabin.result=" + _bookOrderSubCabin__return);


        }
        {
        System.out.println("Invoking getCountryAreaCode...");
        com.springboot.study.service.springairline.GetCountryAreaCodeSearchBean _getCountryAreaCode_searchInfo = null;
        com.springboot.study.service.springairline.GetCountryAreaCodeResultBean _getCountryAreaCode__return = port.getCountryAreaCode(_getCountryAreaCode_searchInfo);
        System.out.println("getCountryAreaCode.result=" + _getCountryAreaCode__return);


        }
        {
        System.out.println("Invoking getOrderSumInfo...");
        com.springboot.study.service.springairline.GetOrderSumInfoQueryBean _getOrderSumInfo_queryInfo = null;
        com.springboot.study.service.springairline.GetOrderSumInfoResultBean _getOrderSumInfo__return = port.getOrderSumInfo(_getOrderSumInfo_queryInfo);
        System.out.println("getOrderSumInfo.result=" + _getOrderSumInfo__return);


        }
        {
        System.out.println("Invoking searchReceptionFlights...");
        com.springboot.study.service.springairline.SearchBeanOfReceptionFlights _searchReceptionFlights_searchInfo = null;
        com.springboot.study.service.springairline.GetBeanOfReceptionFlights _searchReceptionFlights__return = port.searchReceptionFlights(_searchReceptionFlights_searchInfo);
        System.out.println("searchReceptionFlights.result=" + _searchReceptionFlights__return);


        }
        {
        System.out.println("Invoking queryFlightSeatNo...");
        com.springboot.study.service.springairline.FlightSeatNoBean _queryFlightSeatNo_searchInfo = null;
        com.springboot.study.service.springairline.GetRetBeanOfQueryFlightSeatNo _queryFlightSeatNo__return = port.queryFlightSeatNo(_queryFlightSeatNo_searchInfo);
        System.out.println("queryFlightSeatNo.result=" + _queryFlightSeatNo__return);


        }
        {
        System.out.println("Invoking bookSubProdBatch...");
        com.springboot.study.service.springairline.BookSubProdBatchInputBean _bookSubProdBatch_bookInfo = null;
        com.springboot.study.service.springairline.BookSubProdBatchResultBean _bookSubProdBatch__return = port.bookSubProdBatch(_bookSubProdBatch_bookInfo);
        System.out.println("bookSubProdBatch.result=" + _bookSubProdBatch__return);


        }
        {
        System.out.println("Invoking getSpecificPrice...");
        com.springboot.study.service.springairline.GetSpecificPriceInputBean _getSpecificPrice_inputInfo = null;
        com.springboot.study.service.springairline.GetSpecificPriceResultBean _getSpecificPrice__return = port.getSpecificPrice(_getSpecificPrice_inputInfo);
        System.out.println("getSpecificPrice.result=" + _getSpecificPrice__return);


        }
        {
        System.out.println("Invoking getSubProdByTkt...");
        com.springboot.study.service.springairline.InfoBeanOfGetSubProdByTkt _getSubProdByTkt_searchInfo = null;
        com.springboot.study.service.springairline.GetSubProdBySegResultBean _getSubProdByTkt__return = port.getSubProdByTkt(_getSubProdByTkt_searchInfo);
        System.out.println("getSubProdByTkt.result=" + _getSubProdByTkt__return);


        }
        {
        System.out.println("Invoking searchTicketDetail...");
        com.springboot.study.service.springairline.SearchTicketDetailBean _searchTicketDetail_searchInfo = null;
        com.springboot.study.service.springairline.SearchTicketDetailResultBean _searchTicketDetail__return = port.searchTicketDetail(_searchTicketDetail_searchInfo);
        System.out.println("searchTicketDetail.result=" + _searchTicketDetail__return);


        }
        {
        System.out.println("Invoking getFlightSeats...");
        com.springboot.study.service.springairline.FlightSeatsInfoBean _getFlightSeats_searchInfo = null;
        com.springboot.study.service.springairline.GetRetFlightSeatsBean _getFlightSeats__return = port.getFlightSeats(_getFlightSeats_searchInfo);
        System.out.println("getFlightSeats.result=" + _getFlightSeats__return);


        }

        System.exit(0);
    }

}
