package com.springboot.study.service.springairline;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2017-11-23T10:01:49.420+08:00
 * Generated source version: 3.2.1
 * 
 */
@WebServiceClient(name = "SpringServiceSearchBookInterfaceService", 
                  wsdlLocation = "file:/Users/luopan/IdeaProjects/study/src/main/java/com/springboot/study/service/springairline/jike.wsdl",
                  targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/") 
public class SpringServiceSearchBookInterfaceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://wsinterface.remoteservice.booking.springairlines.com/", "SpringServiceSearchBookInterfaceService");
    public final static QName SpringServiceSearchBookInterfacePort = new QName("http://wsinterface.remoteservice.booking.springairlines.com/", "SpringServiceSearchBookInterfacePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/luopan/IdeaProjects/study/src/main/java/com/springboot/study/service/springairline/jike.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SpringServiceSearchBookInterfaceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/luopan/IdeaProjects/study/src/main/java/com/springboot/study/service/springairline/jike.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SpringServiceSearchBookInterfaceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SpringServiceSearchBookInterfaceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SpringServiceSearchBookInterfaceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public SpringServiceSearchBookInterfaceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SpringServiceSearchBookInterfaceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SpringServiceSearchBookInterfaceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns SpringServiceSearchBookInterface
     */
    @WebEndpoint(name = "SpringServiceSearchBookInterfacePort")
    public SpringServiceSearchBookInterface getSpringServiceSearchBookInterfacePort() {
        return super.getPort(SpringServiceSearchBookInterfacePort, SpringServiceSearchBookInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SpringServiceSearchBookInterface
     */
    @WebEndpoint(name = "SpringServiceSearchBookInterfacePort")
    public SpringServiceSearchBookInterface getSpringServiceSearchBookInterfacePort(WebServiceFeature... features) {
        return super.getPort(SpringServiceSearchBookInterfacePort, SpringServiceSearchBookInterface.class, features);
    }

}
