
package com.springboot.study.service.saws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SpringServiceSearchBookInterface", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SpringServiceSearchBookInterface {


    /**
     * 
     * @param searchInfo
     * @return
     *     returns com.springboot.study.service.saws.GetKeguiTotalDescriptionResultBean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getKeguiTotalDescription2", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.GetKeguiTotalDescription2")
    @ResponseWrapper(localName = "getKeguiTotalDescription2Response", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.GetKeguiTotalDescription2Response")
    public GetKeguiTotalDescriptionResultBean getKeguiTotalDescription2(
        @WebParam(name = "searchInfo", targetNamespace = "")
        GetKeguiTotalDescriptionInputBean searchInfo);

    /**
     * 
     * @param searchInfo
     * @return
     *     returns com.springboot.study.service.saws.GetCountryAreaCodeResultBean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCountryAreaCode", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.GetCountryAreaCode")
    @ResponseWrapper(localName = "getCountryAreaCodeResponse", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.GetCountryAreaCodeResponse")
    public GetCountryAreaCodeResultBean getCountryAreaCode(
        @WebParam(name = "searchInfo", targetNamespace = "")
        GetCountryAreaCodeSearchBean searchInfo);

    /**
     * 
     * @param searchInfo
     * @return
     *     returns com.springboot.study.service.saws.SearchFlightsBatchResultBean2
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchFlightsBySegId2", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.SearchFlightsBySegId2")
    @ResponseWrapper(localName = "searchFlightsBySegId2Response", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.SearchFlightsBySegId2Response")
    public SearchFlightsBatchResultBean2 searchFlightsBySegId2(
        @WebParam(name = "searchInfo", targetNamespace = "")
        SearchFlightsBySegIdBean searchInfo);

    /**
     * 
     * @param cancelInfo
     * @return
     *     returns com.springboot.study.service.saws.CancelOrderResultBean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cancelOrder", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.CancelOrder")
    @ResponseWrapper(localName = "cancelOrderResponse", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.CancelOrderResponse")
    public CancelOrderResultBean cancelOrder(
        @WebParam(name = "cancelInfo", targetNamespace = "")
        CancelOrderInputBean cancelInfo);

    /**
     * 
     * @param searchInfo
     * @return
     *     returns com.springboot.study.service.saws.GetSubProdBySegResultBean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSubProdBySeg", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.GetSubProdBySeg")
    @ResponseWrapper(localName = "getSubProdBySegResponse", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.GetSubProdBySegResponse")
    public GetSubProdBySegResultBean getSubProdBySeg(
        @WebParam(name = "searchInfo", targetNamespace = "")
        GetSubProdBySegInputBean searchInfo);

    /**
     * 
     * @param searchInfo
     * @return
     *     returns com.springboot.study.service.saws.GetKeguiTotalDescriptionResultBean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getKeguiTotalDescription", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.GetKeguiTotalDescription")
    @ResponseWrapper(localName = "getKeguiTotalDescriptionResponse", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.GetKeguiTotalDescriptionResponse")
    public GetKeguiTotalDescriptionResultBean getKeguiTotalDescription(
        @WebParam(name = "searchInfo", targetNamespace = "")
        GetKeguiTotalDescriptionInputBean searchInfo);

    /**
     * 
     * @param searchInfo
     * @return
     *     returns com.springboot.study.service.saws.QueryFlightBgAppInfoResultBean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryFlightBgAppInfo", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.QueryFlightBgAppInfo")
    @ResponseWrapper(localName = "queryFlightBgAppInfoResponse", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.QueryFlightBgAppInfoResponse")
    public QueryFlightBgAppInfoResultBean queryFlightBgAppInfo(
        @WebParam(name = "searchInfo", targetNamespace = "")
        QueryFlightBgAppInfoInputBean searchInfo);

    /**
     * 
     * @param searchInfo
     * @return
     *     returns com.springboot.study.service.saws.GetFlightBgAppResultBean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFlightBgApp", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.GetFlightBgApp")
    @ResponseWrapper(localName = "getFlightBgAppResponse", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.GetFlightBgAppResponse")
    public GetFlightBgAppResultBean getFlightBgApp(
        @WebParam(name = "searchInfo", targetNamespace = "")
        GetFlightBgAppInputBean searchInfo);

    /**
     * 
     * @param searchInfo
     * @return
     *     returns com.springboot.study.service.saws.SubmitFlightBgAppResultBean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "submitFlightBgApp2", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.SubmitFlightBgApp2")
    @ResponseWrapper(localName = "submitFlightBgApp2Response", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.SubmitFlightBgApp2Response")
    public SubmitFlightBgAppResultBean submitFlightBgApp2(
        @WebParam(name = "searchInfo", targetNamespace = "")
        SubmitFlightBgAppInputBean searchInfo);

    /**
     * 
     * @param reqBean
     * @return
     *     returns com.springboot.study.service.saws.RetBeanofCreateInvoice
     */
    @WebMethod(operationName = "CreateInvoice")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "CreateInvoice", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.CreateInvoice")
    @ResponseWrapper(localName = "CreateInvoiceResponse", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.CreateInvoiceResponse")
    public RetBeanofCreateInvoice createInvoice(
        @WebParam(name = "reqBean", targetNamespace = "")
        ReqBeanOfCreateInvoice reqBean);

    /**
     * 
     * @param queryInfo
     * @return
     *     returns com.springboot.study.service.saws.GetOrderDetailInfoResultBean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOrderDetailInfo", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.GetOrderDetailInfo")
    @ResponseWrapper(localName = "getOrderDetailInfoResponse", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.GetOrderDetailInfoResponse")
    public GetOrderDetailInfoResultBean getOrderDetailInfo(
        @WebParam(name = "queryInfo", targetNamespace = "")
        GetOrderDetailInfoQueryBean queryInfo);

    /**
     * 
     * @param queryInfo
     * @return
     *     returns com.springboot.study.service.saws.GetTravelBaoJiDetailInfoResultBean1
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTravelBaoJiDetailInfo1", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.GetTravelBaoJiDetailInfo1")
    @ResponseWrapper(localName = "getTravelBaoJiDetailInfo1Response", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.GetTravelBaoJiDetailInfo1Response")
    public GetTravelBaoJiDetailInfoResultBean1 getTravelBaoJiDetailInfo1(
        @WebParam(name = "queryInfo", targetNamespace = "")
        GetTravelBaoJiDetailInfoQueryBean queryInfo);

    /**
     * 
     * @param searchInfo
     * @return
     *     returns com.springboot.study.service.saws.SearchFlightsBatchResultBean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchFlightsBatchSP", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.SearchFlightsBatchSP")
    @ResponseWrapper(localName = "searchFlightsBatchSPResponse", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.SearchFlightsBatchSPResponse")
    public SearchFlightsBatchResultBean searchFlightsBatchSP(
        @WebParam(name = "searchInfo", targetNamespace = "")
        SearchBeanOfSearchFlightsSP searchInfo);

    /**
     * 
     * @param searchInfo
     * @return
     *     returns com.springboot.study.service.saws.GetSubProdBySegResultBean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSubProdByTkt", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.GetSubProdByTkt")
    @ResponseWrapper(localName = "getSubProdByTktResponse", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.GetSubProdByTktResponse")
    public GetSubProdBySegResultBean getSubProdByTkt(
        @WebParam(name = "searchInfo", targetNamespace = "")
        InfoBeanOfGetSubProdByTkt searchInfo);

    /**
     * 
     * @param searchInfo
     * @return
     *     returns com.springboot.study.service.saws.SearchFlightsBatchResultBean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchFlightsBatch", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.SearchFlightsBatch")
    @ResponseWrapper(localName = "searchFlightsBatchResponse", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.SearchFlightsBatchResponse")
    public SearchFlightsBatchResultBean searchFlightsBatch(
        @WebParam(name = "searchInfo", targetNamespace = "")
        SearchFlightsBatchSearchBean searchInfo);

    /**
     * 
     * @param bookInfo
     * @return
     *     returns com.springboot.study.service.saws.BookSubProdBatchResultBean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "bookSubProdBatch", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.BookSubProdBatch")
    @ResponseWrapper(localName = "bookSubProdBatchResponse", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.BookSubProdBatchResponse")
    public BookSubProdBatchResultBean bookSubProdBatch(
        @WebParam(name = "bookInfo", targetNamespace = "")
        BookSubProdBatchInputBean bookInfo);

    /**
     * 
     * @param searchInfo
     * @return
     *     returns com.springboot.study.service.saws.SearchTicketDetailResultBean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchTicketDetail", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.SearchTicketDetail")
    @ResponseWrapper(localName = "searchTicketDetailResponse", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.SearchTicketDetailResponse")
    public SearchTicketDetailResultBean searchTicketDetail(
        @WebParam(name = "searchInfo", targetNamespace = "")
        SearchTicketDetailBean searchInfo);

    /**
     * 
     * @param appInfo
     * @return
     *     returns com.springboot.study.service.saws.ApplyReturnTicketResultBean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "applyReturnTicket", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.ApplyReturnTicket")
    @ResponseWrapper(localName = "applyReturnTicketResponse", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.ApplyReturnTicketResponse")
    public ApplyReturnTicketResultBean applyReturnTicket(
        @WebParam(name = "appInfo", targetNamespace = "")
        ApplyReturnTicketInputBean appInfo);

    /**
     * 
     * @param queryInfo
     * @return
     *     returns com.springboot.study.service.saws.GetTravelBaoJiDetailInfoResultBean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTravelBaoJiDetailInfo", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.GetTravelBaoJiDetailInfo")
    @ResponseWrapper(localName = "getTravelBaoJiDetailInfoResponse", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.GetTravelBaoJiDetailInfoResponse")
    public GetTravelBaoJiDetailInfoResultBean getTravelBaoJiDetailInfo(
        @WebParam(name = "queryInfo", targetNamespace = "")
        GetTravelBaoJiDetailInfoQueryBean queryInfo);

    /**
     * 
     * @param queryInfo
     * @return
     *     returns com.springboot.study.service.saws.QueryOrderInfoForSltResultBean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryOrderInfoForSlt", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.QueryOrderInfoForSlt")
    @ResponseWrapper(localName = "queryOrderInfoForSltResponse", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.QueryOrderInfoForSltResponse")
    public QueryOrderInfoForSltResultBean queryOrderInfoForSlt(
        @WebParam(name = "queryInfo", targetNamespace = "")
        QueryOrderInfoForSltQueryBean queryInfo);

    /**
     * 
     * @param searchInfo
     * @return
     *     returns com.springboot.study.service.saws.GetMoneyClassResultBean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMoneyClass", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.GetMoneyClass")
    @ResponseWrapper(localName = "getMoneyClassResponse", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.GetMoneyClassResponse")
    public GetMoneyClassResultBean getMoneyClass(
        @WebParam(name = "searchInfo", targetNamespace = "")
        GetMoneyClassSearchBean searchInfo);

    /**
     * 
     * @param searchInfo
     * @return
     *     returns com.springboot.study.service.saws.GetRetBeanOfQueryFlightSeatNo
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryFlightSeatNo", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.QueryFlightSeatNo")
    @ResponseWrapper(localName = "queryFlightSeatNoResponse", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.QueryFlightSeatNoResponse")
    public GetRetBeanOfQueryFlightSeatNo queryFlightSeatNo(
        @WebParam(name = "searchInfo", targetNamespace = "")
        FlightSeatNoBean searchInfo);

    /**
     * 
     * @param searchInfo
     * @return
     *     returns com.springboot.study.service.saws.SubmitFlightBgAppResultBean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "submitFlightBgApp", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.SubmitFlightBgApp")
    @ResponseWrapper(localName = "submitFlightBgAppResponse", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.SubmitFlightBgAppResponse")
    public SubmitFlightBgAppResultBean submitFlightBgApp(
        @WebParam(name = "searchInfo", targetNamespace = "")
        SubmitFlightBgAppInputBean searchInfo);

    /**
     * 
     * @param searchInfo
     * @return
     *     returns com.springboot.study.service.saws.SearchFlightsBatchResultBean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchFlightsBySegId", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.SearchFlightsBySegId")
    @ResponseWrapper(localName = "searchFlightsBySegIdResponse", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.SearchFlightsBySegIdResponse")
    public SearchFlightsBatchResultBean searchFlightsBySegId(
        @WebParam(name = "searchInfo", targetNamespace = "")
        SearchFlightsBySegIdBean searchInfo);

    /**
     * 
     * @param reqBean
     * @return
     *     returns com.springboot.study.service.saws.RetBeanOfTktDetail
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryEInvoiceOrders", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.QueryEInvoiceOrders")
    @ResponseWrapper(localName = "queryEInvoiceOrdersResponse", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.QueryEInvoiceOrdersResponse")
    public RetBeanOfTktDetail queryEInvoiceOrders(
        @WebParam(name = "reqBean", targetNamespace = "")
        ReqBeanOfTktDetail reqBean);

    /**
     * 
     * @param cancelInfo
     * @return
     *     returns com.springboot.study.service.saws.CancelFlightBgAppResultBean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cancelFlightBgApp", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.CancelFlightBgApp")
    @ResponseWrapper(localName = "cancelFlightBgAppResponse", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.CancelFlightBgAppResponse")
    public CancelFlightBgAppResultBean cancelFlightBgApp(
        @WebParam(name = "cancelInfo", targetNamespace = "")
        CancelFlightBgAppInputBean cancelInfo);

    /**
     * 
     * @param bookOrderSubCabin
     * @return
     *     returns com.springboot.study.service.saws.BookOrderResultBean
     */
    @WebMethod(operationName = "bookOrder_subCabin")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "bookOrder_subCabin", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.BookOrderSubCabin")
    @ResponseWrapper(localName = "bookOrder_subCabinResponse", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.BookOrderSubCabinResponse")
    public BookOrderResultBean bookOrderSubCabin(
        @WebParam(name = "bookOrder_subCabin", targetNamespace = "")
        BookOrderBookSubCabinBean bookOrderSubCabin);

    /**
     * 
     * @param searchInfo
     * @return
     *     returns com.springboot.study.service.saws.GetOtherFyDetailResultBean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOtherFyDetail", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.GetOtherFyDetail")
    @ResponseWrapper(localName = "getOtherFyDetailResponse", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.GetOtherFyDetailResponse")
    public GetOtherFyDetailResultBean getOtherFyDetail(
        @WebParam(name = "searchInfo", targetNamespace = "")
        GetOtherFyDetailInputBean searchInfo);

    /**
     * 
     * @param searchInfo
     * @return
     *     returns com.springboot.study.service.saws.GetFlightsCanBgResultBean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFlightsCanBg", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.GetFlightsCanBg")
    @ResponseWrapper(localName = "getFlightsCanBgResponse", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.GetFlightsCanBgResponse")
    public GetFlightsCanBgResultBean getFlightsCanBg(
        @WebParam(name = "searchInfo", targetNamespace = "")
        GetFlightsCanBgInputBean searchInfo);

    /**
     * 
     * @param bookInfo
     * @return
     *     returns com.springboot.study.service.saws.BookOrderResultBean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "bookOrder", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.BookOrder")
    @ResponseWrapper(localName = "bookOrderResponse", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.BookOrderResponse")
    public BookOrderResultBean bookOrder(
        @WebParam(name = "bookInfo", targetNamespace = "")
        BookOrderBookBean bookInfo);

    /**
     * 
     * @param appInfo
     * @return
     *     returns com.springboot.study.service.saws.ApplyReturnTicketResultBean2
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "applyReturnTicket2", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.ApplyReturnTicket2")
    @ResponseWrapper(localName = "applyReturnTicket2Response", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.ApplyReturnTicket2Response")
    public ApplyReturnTicketResultBean2 applyReturnTicket2(
        @WebParam(name = "appInfo", targetNamespace = "")
        ApplyReturnTicketInputBean appInfo);

    /**
     * 
     * @param searchInfo
     * @return
     *     returns com.springboot.study.service.saws.GetRetFlightSeatsBean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFlightSeats", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.GetFlightSeats")
    @ResponseWrapper(localName = "getFlightSeatsResponse", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.GetFlightSeatsResponse")
    public GetRetFlightSeatsBean getFlightSeats(
        @WebParam(name = "searchInfo", targetNamespace = "")
        FlightSeatsInfoBean searchInfo);

    /**
     * 
     * @param inputInfo
     * @return
     *     returns com.springboot.study.service.saws.GetSpecificPriceResultBean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSpecificPrice", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.GetSpecificPrice")
    @ResponseWrapper(localName = "getSpecificPriceResponse", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.GetSpecificPriceResponse")
    public GetSpecificPriceResultBean getSpecificPrice(
        @WebParam(name = "inputInfo", targetNamespace = "")
        GetSpecificPriceInputBean inputInfo);

    /**
     * 
     * @param searchInfo
     * @return
     *     returns com.springboot.study.service.saws.XprodBeanOfCheckBindResultBean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getXprodCheckBind", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.GetXprodCheckBind")
    @ResponseWrapper(localName = "getXprodCheckBindResponse", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.GetXprodCheckBindResponse")
    public XprodBeanOfCheckBindResultBean getXprodCheckBind(
        @WebParam(name = "searchInfo", targetNamespace = "")
        XprodBeanOfCheckBindInputBean searchInfo);

    /**
     * 
     * @param reqBean
     * @return
     *     returns com.springboot.study.service.saws.RetBeanofGetInvoice
     */
    @WebMethod(operationName = "GetInvoice")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetInvoice", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.GetInvoice")
    @ResponseWrapper(localName = "GetInvoiceResponse", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.GetInvoiceResponse")
    public RetBeanofGetInvoice getInvoice(
        @WebParam(name = "reqBean", targetNamespace = "")
        ReqBeanOfGetInvoice reqBean);

    /**
     * 
     * @param searchInfo
     * @return
     *     returns com.springboot.study.service.saws.GetSubProdBookedResultBean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSubProdBooked", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.GetSubProdBooked")
    @ResponseWrapper(localName = "getSubProdBookedResponse", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.GetSubProdBookedResponse")
    public GetSubProdBookedResultBean getSubProdBooked(
        @WebParam(name = "searchInfo", targetNamespace = "")
        InfoBeanOfGetSubProdBooked searchInfo);

    /**
     * 
     * @param calcInfo
     * @return
     *     returns com.springboot.study.service.saws.CalcRetTktFeeResultBean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calcRetTktFee", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.CalcRetTktFee")
    @ResponseWrapper(localName = "calcRetTktFeeResponse", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.CalcRetTktFeeResponse")
    public CalcRetTktFeeResultBean calcRetTktFee(
        @WebParam(name = "calcInfo", targetNamespace = "")
        CalcRetTktFeeInputBean calcInfo);

    /**
     * 
     * @param queryInfo
     * @return
     *     returns com.springboot.study.service.saws.GetOrderSumInfoResultBean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOrderSumInfo", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.GetOrderSumInfo")
    @ResponseWrapper(localName = "getOrderSumInfoResponse", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.GetOrderSumInfoResponse")
    public GetOrderSumInfoResultBean getOrderSumInfo(
        @WebParam(name = "queryInfo", targetNamespace = "")
        GetOrderSumInfoQueryBean queryInfo);

    /**
     * 
     * @param searchInfo
     * @return
     *     returns com.springboot.study.service.saws.GetBeanOfReceptionFlights
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchReceptionFlights", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.SearchReceptionFlights")
    @ResponseWrapper(localName = "searchReceptionFlightsResponse", targetNamespace = "http://wsinterface.remoteservice.booking.springairlines.com/", className = "com.springboot.study.service.saws.SearchReceptionFlightsResponse")
    public GetBeanOfReceptionFlights searchReceptionFlights(
        @WebParam(name = "searchInfo", targetNamespace = "")
        SearchBeanOfReceptionFlights searchInfo);

}
